version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: iot-xray-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: iot-xray
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - iot-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: iot-xray-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - iot-network

volumes:
  mongodb_data:
  rabbitmq_data:

networks:
  iot-network:
    driver: bridge
